language: python
sudo: false
python:
    - 2.7
    - 3.4
    - 3.5
    - 3.6
    - 3.7-dev
install:
    - pip install coverage coveralls -e .[test]
script:
    - coverage run -m nose
after_success:
    - coveralls
notifications:
    email: false
